name: Release npm package

on:
  push:
    tags:
    - 'v*'

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.1'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-        
    - name: Release
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        bash build.sh
        npm publish --access=public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
