name: Release npm package

on:
  push:
    tags:
    - 'v*'

jobs:
  pkg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.1'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Release
      run: |
        wget https://github.com/upx/upx/releases/download/v4.0.0/upx-4.0.0-amd64_linux.tar.xz
        tar -xvf upx-4.0.0-amd64_linux.tar.xz
        chmod +x upx-4.0.0-amd64_linux/upx
        sudo cp upx-4.0.0-amd64_linux/upx /usr/local/bin/
        npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        bash build.sh
        echo "appthreat:registry=https://npm.pkg.github.com" > ~/.npmrc
        npm publish --access=public --@appthreat:registry='https://npm.pkg.github.com'
        echo "appthreat:registry=https://registry.npmjs.org" > ~/.npmrc
        npm publish --access=public --@appthreat:registry='https://registry.npmjs.org'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_OPTIONS: --max_old_space_size=4096
