name: Build npm package

on:
  pull_request:

jobs:
  pkg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org/
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.19.8'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: |
        wget https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
        tar -xvf upx-4.2.2-amd64_linux.tar.xz
        chmod +x upx-4.2.2-amd64_linux/upx
        sudo cp upx-4.2.2-amd64_linux/upx /usr/local/bin/
        bash build.sh
        pip3 install blint
        blint -i plugins -o /tmp/reports
        npm publish --dry-run
        pushd packages/windows-amd64
        npm publish --dry-run
        popd
        pushd packages/linux-arm64
        npm publish --dry-run
        popd
        pushd packages/windows-arm64
        npm publish --dry-run
        popd
        pushd packages/darwin-arm64
        npm publish --dry-run
        popd
        pushd packages/ppc64
        npm publish --dry-run
        popd
  winpkg:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org/
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.19.8'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: |
        .\build.ps1
